# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a4e7120fd49f0c5557e8f85a06c8219ab3f67ed1ddcd261a8a50887af96220b2279d1c450f120559795ce78a802adbcf6ca0ad2954e02d72e065cdaf6614c2c

test:
  secret_key_base: f85374525724b14bcb197d7c4f945edcb4e89b52e038b96ea150aba8c7afe75fd68b6e21ee1d86544f365d9fb2de2ecc64373764ae75484ae5b9a66b7315bf92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
