# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1abe2a9c775d8389a14f0fe721e80f8f2d70cfe98f70792c2325c17cac3f8d815993b8c7ae9b1a3cee7726e0aed6925428de3edeb1c8788e6c4a03d7f6cdc710

test:
  secret_key_base: cf7221e26cbe30f5c1bdea3d0967a9ee8944a72172f66fe724de600c616f7389ddfaa77fa92d5d140d2d84cd27dd3650144fcefb8952644baab803b946e3158e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
